# config/hydra.yaml
serve:
  public:
    port: 4444
    cors:
      enabled: true
      allowed_origins:
        - http://localhost:5555
      allowed_methods:
        - POST
        - GET
        - PUT
        - DELETE
        - OPTIONS
  admin:
    port: 4445

urls:
  self:
    issuer: http://localhost:4444/
  consent: http://localhost:3000/consent
  login: http://localhost:3000/login
  logout: http://localhost:3000/logout

secrets:
  system:
    - nofreefoodinfreetown

oidc:
  subject_identifiers:
    supported_types:
      - pairwise
      - public
    pairwise:
      salt: nofreefoodinfreetown
      
ttl:
  login_consent_request: 1h
  access_token: 1h
  refresh_token: 720h
  id_token: 1h
  auth_code: 15m

strategies:
  access_token: jwt

log:
  level: debug
  format: json